name: Deploy to ECS 
on:
    push:
      branches:
        main
    workflow_dispatch:
jobs:
   builddeploytoecs:
      runs-on: ubuntu-latest
      permissions:
        contents: read 
        packages: write  
      steps:
        ### clone the code from the runner 
        - name: checkout code from repo 
          uses: actions/checkout@v3
        ### setup java and maven 
        - name: setup java and maven environment    
          uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '11'  
        ### use maven to package artifact, when these step executes the artifact should be created. 
        - name: package with maven 
          run: mvn package 
        ### use sonarqube to do code analysis. Ensure that you have a sonarqube server running and you've created a project. 
        - name: code analysis with sonarqube
          run: mvn sonar:sonar -Dsonar.projectKey=xashy-webapp -Dsonar.host.url=${{secrets.MY_URL_LINK}} -Dsonar.token=${{secrets.YOUR_TOKEN_ONE}}
        ## Upload to github packages and ensure that you update the pom.xml at the level of distrubution management.
        - name: Upload to github packages
          run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        ## set up authenticate to aws. make sure you create a secret for accesskey, secretkey and region